############################
#                          #
#      MEDIA PLAYERS       #
#                          #
############################

###############
#    VIDEO    #
###############


# - platform: kodi
#   host: 192.168.0.155
#   name: Kodi
#   username: kodi
#   password: !secret libreelecpassword
#   turn_off_action:
#   service: media_player.kodi_call_method
#   # data_template:
#   #   entity_id: '{{ entity_id }}'
#   #   method: System.Shutdown
#   enable_websocket: true

- platform: samsungtv
  name: ue46es8005
  host: 192.168.0.40
  # port: 55000
  # mac: !secret ue46es8005_mac # invalid since ~0.88?

# - platform: samsungtv
#   name: ue55nu7475xxc
#   host: 192.168.0.47
#   port: 8001
#   mac: !secret samsung_UE55NU7475XXC

- platform: samsungtv_tizen # Uses HACS - https://github.com/jaruba/ha-samsungtv-tizen
  host: 192.168.0.47
  port: 8002
  mac: !secret samsung_UE55NU7475XXC

#- platform: braviatv
#  name: sony_bravia
#  host: 192.168.0.10
#  mac: !secret sony_bravia_mac
