############################
#                          #
#      MEDIA PLAYERS       #
#                          #
############################

###############
#    VIDEO    #
###############


# - platform: androidtv
#   host: 192.168.0.44
#   name: tcl55Ddc760
#   adb_server_ip: 127.0.0.1
#   adb_server_port: 5555 #5037
#   apps:
#     "amazon": "Amazon Premium Video"

# - platform: androidtv
#   host: 192.168.0.44
#   name: TCL55DDC760
#   # adbkey: /config/adbkey
#   apps:
#     "amazon": "Amazon Premium Video"
#     # "hbo": "HBO Nordic"
#     # "netflix": "Netflix"

# - platform: kodi
#   host: 192.168.0.155
#   name: Kodi
#   username: kodi
#   password: !secret libreelecpassword
#   turn_off_action:
#   service: media_player.kodi_call_method
#   # data_template:
#   #   entity_id: '{{ entity_id }}'
#   #   method: System.Shutdown
#   enable_websocket: true

- platform: samsungtv
  name: ue46es8005
  host: 192.168.0.40
  # port: 55000
  # mac: !secret ue46es8005_mac # invalid since ~0.88?

- platform: samsungtv
  name: ue55nu7475xxc
  host: 192.168.0.47
  port: 8001
  mac: !secret ue55nu7475xxc_mac

#- platform: braviatv
#  name: sony_bravia
#  host: 192.168.0.10
#  mac: !secret sony_bravia_mac
