############################
#                          #
#      BINARY SENSORS      #
#                          #
############################

###################
#    Floorplan    #
###################

- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan

#- platform: mqtt
#  state_topic: floorplan/floorplan
#  name: Floorplan

#- platform: mqtt
#  state_topic: floorplan/floorplan_2
#  name: Floorplan_2


###################
#    Occupancy    #
###################

- platform: bayesian
  prior: 0.1
  probability_threshold: 0.9
  name: 'Baysian Aephir Home'
  observations:
    - entity_id: 'device_tracker.google_maps_110730659630480268471'
      prob_given_true: 0.6
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.aephir_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'

#- platform: mqtt
#  state_topic: "wallpanel/mywallpanel/sensor/motion"
#  name: "Motion"
#  payload_on: '{"value":true}'
#  payload_off: '{"value":false}'
#  device_class: motion

- platform: template
  sensors:
    kristinahome:
      friendly_name: Is kristina Home
      value_template: >-
          {%- if is_state("input_boolean.kristinahome", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}

- platform: template
  sensors:
    aephirhome:
      friendly_name: Is Aephir Home
      value_template: >-
          {%- if is_state("input_boolean.aephirhome", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}

- platform: template
  sensors:
    someonehome360:
      friendly_name: Is Anyone Home
      value_template: >-
          {%- if is_state("input_boolean.someonehome", "on") -%}
          true
          {%- else -%}
          false
          {%- endif %}

##############
#    Ping    #
##############

- platform: ping
  name: Ping Google DNS
  host: 8.8.8.8

- platform: ping
  name: Ping Router
  host: 192.168.0.1

- platform: ping
  name: Ping HASSio
  host: 192.168.0.102

#################
#    Sensors    #
#################

- platform: template
  sensors:
    walk_in_closet_motion_sensor:
      friendly_name: "Walk-in Closet Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.aeotec_zw100_multisensor_6_burglar', '8') }}"

- platform: template
  sensors:
    conservatory_motion_sensor_aeotec:
      friendly_name: "Conservatory 2 Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.aeotec_zw100_multisensor_6_burglar_2', '8') }}"

#################
#    SkyBell    #
#################

- platform: skybell
  monitored_conditions:
    - button
    - motion
