########
#    Camera mjpeg

- platform: mjpeg
  mjpeg_url: http://192.168.0.46:2971/camera/stream
  name: WallPanel Camera
  # stream_source: http://192.168.0.46:2971/camera/stream
#  username: !secret android_ip_cam_user
#  password: !secret android_ip_cam_pass

# - platform: reolink_dev
#   host: 192.168.0.67 #191.168.0.67
#   username: !secret reolink_admin_user # default: admin
#   password: !secret reolink_password
#   name: chicken_coop
#   stream: main # sub # (optional, default main)
#   protocol: rtmp # rtsp # (optional, default rtmp)
#   # channel: NVR camera channel (optional, default 0)
#   scan_interval: 5 # (optional, default 30s)

# - platform: mjpeg
#   mjpeg_url: http://192.168.0.212/
#   name: ESP EYE

# - platform: ffmpeg
#   # still_image_url: http://192.168.0.51:8080/
#   name: Wyze2
#   input: !secret wyze_rtsp_input
#   # username: !secret wyze_rtsp_user
#   # password: !secret wyze_rtsp_pass

#
# - platform: generic
#   still_image_url: "null"
#   name: Wyze2
#   stream_source: !secret wyze_rtsp_url
#   username: !secret wyze_rtsp_user
#   password: !secret wyze_rtsp_pass

# - platform: mjpeg
#   mjpeg_url: !secret octoprint_stream_url
#   still_image_url: !secret octoprint_still_url
#   name: OctoPrint

- platform: ffmpeg
  input: !secret octoprint_stream_url
  name: OctoPrint

- platform: ffmpeg
  input: !secret wyze_rtsp_url
  # name: Wyze2

# - platform: ffmpeg # Wyze??


# # https://community.home-assistant.io/t/wyze-cam-integration-with-home-assistant-without-flashing/65651
# # Wyze Cam - Only works if I have tinyCam app do a webserver
# - name: Wyze Camera 1
#   platform: mjpeg
#   mjpeg_url: !secret tinycam_wyze_cam_1_url
# #  username: !secret wyze_user
# #  password: !secret wyze_pass
# #  mjpeg_url: !secret wyze_cam_url

- platform: skybell
