#################
#               #
#    Climate    #
#               #
#################

- platform: zwave


# - platform: generic_thermostat
#   name: Bathroom
#   heater: climate.fibaro_system_fgt001_heat_controller_heating
#   target_sensor: sensor.temperature_158d00022c66ff
