####################
#                  #
#      LIGHTS      #
#                  #
####################

- platform: hue
  host: 192.168.0.10
  allow_unreachable: true

- platform: yeelight
  devices:
    192.168.0.201:
      name: Living Room Lightstrip

- platform: skybell

##########################
#      LIGHT GROUPS      #
##########################

- platform: group
  name: All Lights
  entities:
    - light.main_floor_lights
    - light.basement_lights
    - light.top_floor_lights
    - light.outdoor_lights

#######################
#__Main_Floor_Lights__#

- platform: group
  name: Main Floor Lights
  entities:
    - light.kitchen_lights
    - light.dining_room_lights
    - light.conservatory_lights
    - light.bedroom_lights
    - light.baby_room_lights
    - light.entrance_lights

- platform: group
  name: kitchen lights
  entities:
    - light.kitchen_spots
    - light.kitchen_cabinet_lights

- platform: group
  name: Dining Room Lights
  entities:
    - light.living_room_lightstrip
    - light.dining_table_lights

- platform: group
  name: Conservatory Lights
  entities:
    - light.conservatory_couch
    - light.conservatory_reading

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom

- platform: group
  name: Baby Room Lights
  entities:
    - light.baby_room
    - light.changing_table

- platform: group
  name: Changing Table
  entities:
    - light.changing_table_1

- platform: group
  name: Kitchen Spots
  entities:
    - light.kitchen_spot_1
    - light.kitchen_spot_2
    - light.kitchen_spot_3
    - light.kitchen_spot_4
    - light.kitchen_spot_5
    - light.kitchen_spot_6

- platform: group
  name: Kitchen Cabinet Lights
  entities:
    - light.kitchen_cabinet_1
    - light.kitchen_cabinet_2

- platform: group
  name: Dining Table lights
  entities:
    - light.dining_table_1
    - light.dining_table_2

- platform: group
  name: Entrance Lights 1
  entities:
    - light.entrance_1_1
    - light.entrance_1_2

- platform: group
  name: Entrance Lights 2
  entities:
    - light.entrance_2_1
    - light.entrance_2_2

- platform: group
  name: Entrance Lights
  entities:
    - light.entrance_lights_1
    - light.entrance_lights_2


#####################
#__Basement_Lights__#

- platform: group
  name: Basement Lights
  entities:
    - light.tv_room_lights
    - light.basmenent_entrance
    - light.basement_hallway
    - light.wine_cellar_lights
    - light.walkin_closet
    - light.stairway_down

- platform: group
  name: TV Room Lights
  entities:
    - light.tv_room

- platform: group
  name: Wine Cellar Lights
  entities:
    - light.wine_cellar

- platform: group
  name: Basement Entrance Lights
  entities:
    - light.basement_entrance
    - light.basement_hallway

- platform: group
  name: Basement Pathway
  entities:
    - light.basement_entrance
    - light.tv_room

######################
#__Top_Floor_Lights__#

- platform: group
  name: Top Floor Lights
  entities:
    - light.top_floor_bathroom_lights
    - light.top_floor_tv_area
    - light.top_floor_hallway
    - light.stairway_up

- platform: group
  name: Top Floor Bathroom Lights
  entities:
    - light.top_floor_bathroom

- platform: group
  name: Stairway Up
  entities:
    - light.top_stairway_1
    - light.top_stairway_2

- platform: group
  name: Top Floor TV Area
  entities:
    - light.top_tv_area_1
    - light.top_tv_area_2
    - light.top_tv_area_3

- platform: group
  name: Top Floor Hallway
  entities:
    - light.top_hallway_1
    - light.top_hallway_2
    - light.top_hallway_3

####################
#__Outdoor_Lights__#

- platform: group
  name: Outdoor Lights
  entities:
    - light.east_garden
    - light.west_garden
    - light.outside_shed
    - light.outside_basement_entrance
