######################
#                    #
#    TELEGRAM BOT    #
#                    #
######################

- platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatID_Aephir
