#################
#    Devices    #
#################

#- platform: template
#  sensors:
#    battery_MYPHONEID:
#      unit_of_measurement: '%'
#      value_template: >-
#          {%- if states.device_tracker.aephirs7edge.attributes.battery %}
#              {{ states.device_tracker.aephirs7edge.attributes.battery|round }}
#          {% else %}
#              Unknown
#          {%- endif %}

#- platform: mqtt
#  state_topic: "owntracks/aephir/phone"
#  name: "Aephir Phone Battery"
#  unit_of_measurement: "%"
#  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/Walden/cd926e1b-0476-46b9-86d2-f0c0c3e7d530"
#  state_topic: !secret aephir_life360_bat_id
  name: "Aephir Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/KristinaBrody/612a3f1e-8eae-425e-9cc5-14e48649cc46"
  name: "Kristina Phone Battery 360"
  unit_of_measurement: "%"
#  value_template: "{{ value_json.batt | round(0) }}"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/Emilie/aa172623-f9cd-406b-9007-dc08461d2c24"
  name: "Emilie Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ (value_json.batt | float) | round(0) }}"

- platform: template
  sensors:
    samsung_ue55nu7475xxc_dummy:
      value_template: >-
          '{% if is_state("media_player.ue55nu7475xxc", "unavailable") %}off{% elif is_state("media_player.ue55nu7475xxc", "off")%}off{% else %}on{% endif %}'
      friendly_name: 'Conservatory TV'
      # icon_template: >-
      #   {% if is_state('media_player.ue55nu7475xxc','on') %}
      #     mdi:television
      #   {% else %}
      #     mdi:television
      #   {% endif %}

- platform: template
  sensors:
    samsung_ue46es8005_dummy:
      value_template: >-
          '{% if is_state("media_player.upstairs_living_room_tv", "unavailable") %}off{% elif is_state("media_player.upstairs_living_room_tv", "off")%}off{% else %}on{% endif %}'
      friendly_name: 'Upstairs TV'
      # icon_template: >-
      #   {% if is_state('media_player.ue55nu7475xxc','on') %}
      #     mdi:television
      #   {% else %}
      #     mdi:television
      #   {% endif %}
